package com.mabdelhamid.illamovies.base

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.viewbinding.ViewBinding

/**
 * A base class to be inherited by all fragments in the app.
 *
 * @param BINDING the binding class of the activity that is generated by viewBinding.
 * @property inflateMethod the inflate method of the binding class.
 */

abstract class BaseFragment<BINDING : ViewBinding>(
    private val inflateMethod: (LayoutInflater, ViewGroup?, Boolean) -> BINDING
) : Fragment() {

    private var _binding: BINDING? = null
    protected val binding: BINDING get() = requireNotNull(_binding)

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = inflateMethod(inflater, container, false)
        return binding.root
    }

    override fun onDestroyView() {
        _binding = null
        super.onDestroyView()
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        initUi()
        initObservers()
    }

    abstract fun initUi()

    abstract fun initObservers()
}