package com.mabdelhamid.illamovies.base

import android.os.Bundle
import android.view.LayoutInflater
import androidx.appcompat.app.AppCompatActivity
import androidx.viewbinding.ViewBinding
import com.mabdelhamid.illamovies.R
import com.mabdelhamid.illamovies.util.extension.changeBarsColor

/**
 * A base class to be inherited by all activities in the app.
 *
 * @param BINDING the binding class of the activity that is generated by viewBinding.
 * @property inflateMethod the inflate method of the binding class.
 */

abstract class BaseActivity<BINDING : ViewBinding>(
    private val inflateMethod: (LayoutInflater) -> BINDING
) : AppCompatActivity() {

    private var _binding: BINDING? = null
    protected val binding: BINDING get() = requireNotNull(_binding)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        _binding = inflateMethod(layoutInflater)
        setContentView(binding.root)
        initUi()
        initObservers()
    }

    override fun onStart() {
        super.onStart()
        changeBarsColor(color = R.color.white, isLightBars = true, view = binding.root)
    }

    override fun onDestroy() {
        _binding = null
        super.onDestroy()
    }

    abstract fun initUi()

    abstract fun initObservers()
}